<?php
require_once dirname(__FILE__).'/../../lib/Connection.php';

/**
 * Test class for Helios_Connection.
 * Generated by PHPUnit on 2010-02-07 at 11:12:18.
 */
class Helios_ConnectionTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Helios_Connection
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp( )
    {
        Helios::configure( dirname( __FILE__ ) . '/../config/good.yml' );

        $this->object = Helios_Connection::getInstance( );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown( )
    {
        Helios::destroy( );
    }

    /**
     *
     */
    public function testGetInstance( )
    {
        $this->assertTrue( Helios_Connection::getInstance( ) instanceof Helios_Connection );
    }

    /**
     *
     */
    public function testInitialize( )
    {
        $this->assertTrue( $this->object->initialize( ) );

        $this->assertTrue( $this->object->getService( ) instanceof Apache_Solr_Service_Balancer );
    }

    /**
     * @depends testGetInstance
     */
    public function testGetAutoCommit( )
    {
        $this->object->setAutoCommit( true );

        $this->assertTrue( $this->object->getAutoCommit() == true );
    }

    /**
     * @depends testGetInstance
     */
    public function testSetAutoCommit( )
    {
        $this->object->setAutoCommit( true );

        $this->assertTrue( $this->object->getAutoCommit() == true );
    }


}
