<?php
require_once dirname(__FILE__).'/../../lib/Request.php';

/**
 * Test class for Helios_Request.
 * Generated by PHPUnit on 2010-02-10 at 13:33:22.
 */
class Helios_RequestTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Helios_Request
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Helios_Request;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testExecute().
     */
    public function testExecute()
    {

    }

    /**
     *
     */
    public function testGetQuery()
    {
        $query = 'test:query';

        $this->object->setQuery( $query );

        $this->assertEquals( $query, $this->object->getQuery( ) );
    }

    /**
     *
     */
    public function testSetValidQuery()
    {
        $query = 'test:query';

        $this->object->setQuery( $query );

        $this->assertEquals( $query, $this->object->getQuery( ) );
    }

    /**
     *
     */
    public function testSetInvalidQuery()
    {
        $query = array( );

        $failure = false;

        try
        {
            $this->object->setQuery( $query );
        }
        catch ( Exception $e )
        {
            $failure = true;
        }

        $this->assertTrue( $failure );
    }
}
