<?php

namespace Helios\Test;

use     Helios\Collection,
        Helios\Document,
        Helios\Helios,
        Helios\Facet,
        Helios\Request;
/**
 * Test class for Helios_Collection.
 * Generated by PHPUnit on 2010-02-10 at 13:35:50.
 */
class CollectionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Collection
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Collection;

        $rawResponse = file_get_contents( dirname(__FILE__) . '/../data/simpleResponse.json' );

        $this->response = new \Apache_Solr_Response( new \Apache_Solr_HttpTransport_Response( 200, 'Content-Type: text/plain; charset=UTF-8', $rawResponse ), false  );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     *
     */
    public function testGetSetRequest()
    {
        $request = new Request;

        $this->object->setRequest( $request );

        $this->assertEquals( $request, $this->object->getRequest( ) );
    }

    /**
     *
     */
    public function testSetInvalidRequest()
    {
        $this->setExpectedException("Exception");
        $this->object->setRequest( $request );
    }

    /**
     *
     */
    public function testGetSetResponse()
    {
        $this->object->setResponse( $this->response );

        $this->assertEquals( $this->response, $this->object->getResponse( ) );
    }


    /**
     *
     */
    public function testSetInvalidResponse()
    {
        $this->setExpectedException("Exception");
        $this->object->setResponse( $response );
    }



    /**
     *
     */
    public function testGetSetRecords()
    {
        $documents = array( );

        $document = new Document( array( Helios::ID_FIELD_NAME => 1,
                                                Helios::TYPE_FIELD_NAME => 'some_type') );
        array_push( $documents, $document );

        $document = new Document( array( Helios::ID_FIELD_NAME => 2,
                                                Helios::TYPE_FIELD_NAME => 'some_type') );
        array_push( $documents, $document );



        $this->object->setRecords( $documents );

        // test iteration
        foreach ( $this->object->getRecords() as $document )
        {
            $this->assertTrue( $document instanceof Document );
        }

        // test countable
        $this->assertEquals( 2, count( $this->object->getRecords() ) );

        $this->assertEquals( $documents, $this->object->getRecords() );
    }

    /**
     *
     */
    public function testGetSetFacetFields()
    {
        $facets = array( new Facet( ) );

        $this->object->setFacetFields( $facets );

        $this->assertEquals( $facets, $this->object->getFacetFields( ) );
    }

    /**
     *
     */
    public function testGetSetFacetQueries()
    {
        $facets = array( new Facet( ) );

        $this->object->setFacetQueries( $facets );

        $this->assertEquals( $facets, $this->object->getFacetQueries( ) );
    }

    /**
     *
     */
    public function testGetSetFacetDates()
    {
        $facets = array( new Facet( ) );

        $this->object->setFacetDates( $facets );

        $this->assertEquals( $facets, $this->object->getFacetDates( ) );
    }

    public function testGetSetFacetRanges()
    {
        $facets = array( new Facet( ) );

        $this->object->setFacetRanges( $facets );

        $this->assertEquals( $facets, $this->object->getFacetRanges( ) );
    }

    /**
     * Assert paginator function
     */
    public function testPaginatiorFunction()
    {
        $request = new Request();
        $request->setLimit( 10 );
        $request->setCurrentPage( 2 );

        $this->object->setRequest( $request );

        $this->assertEquals( $this->object->getRequest(), $request );
        $this->assertEquals( $this->object->getPageSize(), $request->getLimit() );
        $this->assertEquals( $this->object->getCurrentPage(), $request->getCurrentPage() );
        $this->assertEquals( $this->object->getNumRecords(), 0 );

        /* Division by zero */
        $request->setLimit( 0 );
        $this->assertEquals( $this->object->getPageCount(), 0 );
    }

    public function testAreRecordsGrouped()
    {
        $request = new \Helios\Request();
        $request->setParams( array( 'group' => "true" ) );

        $this->object->setRequest( $request );

        $this->assertEquals( true, $this->object->areRecordsGrouped() );

        $request = new \Helios\Request();
        $this->object->setRequest( $request );
        $this->assertEquals( false, $this->object->areRecordsGrouped() );
    }

}
